### ISSUE TITLE
排序不能这样写了，一定要严格返回 -1，0，1 三类值

### ISSUE THREAD

**Issue by gMan1990** [cljnnn/tampermonkey-script#1]
- 这个好像不对，貌似 `vx>vy` 可行
    https://github.com/cljnnn/tampermonkey-script/blob/5804757387b2b590aae991223f595c672492b077/v2ex/sort.js#L19
- 但各浏览器上表现不一致，所以还是返回三类值准确
    > [於是我們來做一個實驗來看看參數到底是什麼](https://medium.com/@realdennis/javascript-%E5%BE%9Earray%E7%9A%84sort%E6%96%B9%E6%B3%95-%E8%81%8A%E5%88%B0%E5%90%84%E5%AE%B6%E7%80%8F%E8%A6%BD%E5%99%A8%E7%9A%84%E5%AF%A6%E4%BD%9C%E7%AE%97%E6%B3%95-c23a335b1b80)

----
ps: 还有这个排序调整感觉有点影响正常读贴，本来是按正常楼层顺序读的。不知有木有其它更好的办法。比如复制一份放在右侧边栏？

**Comment by cljnnn** [comment]
这个确实有问题，在chrome上不能工作，谢谢你的资料，我已经更新脚本了。
